### PR TITLE
Correct BelongsTo relation creation

### PR DESCRIPTION
**Pull request by 090809**
Closes: #415
Closes: #412

### CODE REVIEW

**Comment by 090809** [comment]
@SBShane this test case needs to create :inmemory: db with migrations, so it failes. So here I'm stuck

**Comment by 090809** [comment]
Some nested data loading (in factory configuring) is workaround about #321 problem, so we can fix it clearly with real call of `->load($relations)` in `$factory->create()` (tested it with supposed test)

**Comment by shalvah** [comment]
Hmm, I'll take a look at this and see what I can do.

**Comment by shalvah** [comment]
Well done! I see you've put in a lot of work on the tests, but your change seems pretty innocuous, so I think we can live without the tests.

**Comment by 090809** [comment]
@shalvah You did not delete the `afterTestCleanup` function in tests, now it unused

**Comment by shalvah** [comment]
Deleted it on master.

**Comment by shalvah** [comment]
If we add more features that rely on the database, we may eventually add these database tests back, and your work might come in handy. Thanks!

**Pull request merged**
