### PR TITLE
Ability to add cursor pagination

### PR DESCRIPTION
**Pull request by fikri-kompanion**
Extend model pagination with cursor pagination.

Example: 

```
@apiResourceModel App\Models\User paginate=10,cursor
```

### CODE REVIEW

**Comment by shalvah** [comment]
You need to add tests 😬

**Comment by shalvah** [comment]
Hey, are you still interested in adding this? Do you need help adding tests?

**Comment by fikri-kompanion** [comment]
@shalvah that would be good

**Comment by shalvah** [comment]
Still open to merging this once a test is added. (Sorry, I'm fairly busy, so can't do much myself.)

**Comment by olivernybroe** [comment]
@shalvah no worries at all, thank you for all the work you do maintaining this project! 

I have opened a PR which adds tests for it and updated the attribute.

**Pull request closed without merging**
