### PR TITLE
Refactor sidebar and external JS to improve usability and performance. Closes #351

### LINKED ISSUE #351: Improvement: rewrite/refactor/upgrade sidebar search and scroll/id matching
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

I've found the sidebar and the subsequent id-scroll matching to be kinda janky. I think I have seen this complaint in other places (https://github.com/knuckleswtf/scribe/issues/305, https://github.com/knuckleswtf/scribe/issues/326) so maybe it might be worth doing a rewrite of the sidebar? 

I can take a crack at it. I don’t think I would change the structure (or design) of the sidebar but just the underlying JS (search, scroll, id updates, etc) to make it work in a modern way.

Any thoughts?

### PR DESCRIPTION
**Pull request by james2doyle**
Keeping this open so people can give this branch a shot and see if it is going in the right direction

- [x] remove jquery dependency
- [x] move some inline scripts into the external js file
- [x] replace sidebar search with [jets.css](https://jets.js.org/) which is near instant search
- [x] sidebar is now rendered as HTML
- [x] use hashchange event to track ids and update sidebar
- [x] add link on h2 tags
- [x] add emoji on cancel button to fix spacing
- [x] handle multiple languages (fixed bug where languages with the same highlight syntax would conflict)
- [x] handle mobile case/menu
- [x] cross-browser testing (Chrome, Safari, Firefox)
- [ ] remove unused styles

### CODE REVIEW

**Comment by ezralazuardy** [comment]
@james2doyle i've tried this and the issue seems to be fixed. nicely done, thanks 💖

**Comment by james2doyle** [comment]
This is ready for a more indepth test. Been using it on a large project myself. Looks good so far. Definitely snappier in some cases. It would be nice to have a variety of people test it out

**Comment by james2doyle** [comment]
If this seems good to go, I can remove the unused CSS and wrap this up. If you wanted some GIFs of this working I can add those as well

**Comment by james2doyle** [comment]
Anything else I need to do to get this merged?

**Comment by shalvah** [comment]
Ah, is it ready to go? Okay then, let's give it a shot. Well done.

(If you're interested, another thing I'd personally like to do is get rid of HighlightJS (it's really poor on partial code snippets) and replace with probably Prism. Tried once but couldn't make it work with the current styling. I'll probably just wait until I can make a new theme entirely.)

**Comment by james2doyle** [comment]
Ok great. I've used it before so I can take a look

**Pull request merged**
