### PR TITLE
Document objects

### PR DESCRIPTION
**Pull request by wjonkerhulst**
Right now the following syntax for array's is allowed :
```
@bodyParam data array required The import payload in JSON. Example: [{"order":{"unique_id":"1838473","order_date":20201007,"order_time":94945,"user_company_number":29}}]
```
I would like to also document objects, this change would make the following example valid :
```
@bodyParam data array required The import payload in JSON. Example: {"order":{"unique_id":"1838473","order_date":20201007,"order_time":94945,"user_company_number":29}}
```

### CODE REVIEW

**Comment by shalvah** [comment]
You *can* document objects already. Is the documentation on that unclear? https://scribe.readthedocs.io/en/latest/documenting/documenting-endpoint-body-parameters.html#handling-array-and-object-parameters

Also, have you seen the changes coming in v2? In v2, your first example should have type `object[]`, not `array`. https://scribe.readthedocs.io/en/v2/migrating-v2.html#migration-required-new-syntax-for-array-and-object-parameters

**Comment by shalvah** [comment]
So, thanks for the PR, but gonna have to close this. 🤷‍♂️

It seems you didn't know about the allowed syntax. Was it a problem with the documentation (hard to find, hard to understand)? Or did you just assume that was the syntax without checking?

**Comment by wjonkerhulst** [comment]
Hey, I did read about the object, wat I do not understand is how I should write an example for an object.

For example.
```
@bodyParam data object required The import payload in JSON. Example: {"order":{"unique_id":"1838473","order_date":20201007,"order_time":94945,"user_company_number":29}}
```

Will output the following : 
image

I would like to have it as following :
image

**Comment by shalvah** [comment]
Have you tried with v2?

**Comment by wjonkerhulst** [comment]
Thanks for the tip. I will test v2 today or tomorrow and report back te outcome.

**Comment by wjonkerhulst** [comment]
Hey, this did solve the problem. Thanks.
image

**Pull request closed without merging**
