### PR TITLE
PHP 8 compatibility

### PR DESCRIPTION
**Pull request by shalvah**
- Renamed `Match` class to `MatchedRoute`
- Added type guard for union types when fetching parameter class names

### CODE REVIEW

**Comment by dacopavlov** [comment]
Any chance this fix to be released?

**Comment by shalvah** [comment]
🤨
https://github.com/knuckleswtf/scribe/releases/tag/2.5.1

**Comment by dacopavlov** [comment]
@shalvah there is a problem with faker, it not support php 8:

Problem 1                                                                                                                                                                                                                                                                         - fakerphp/faker[v1.9.1, ..., 1.9.x-dev] require php ^5.3.3 \|\| ^7.0 -> your php version (8.0.0) does not satisfy that requirement.                                                                                                                                              - fzaninotto/faker[v1.9.1, ..., v1.9.2.x-dev] require php ^5.3.3 \|\| ^7.0 -> your php version (8.0.0) does not satisfy that requirement.                                                                                                                                         - Root composer.json requires knuckleswtf/scribe ^2.5 -> satisfiable by knuckleswtf/scribe[2.5.1].                                                                                                                                                                              - knuckleswtf/scribe 2.5.1 requires fakerphp/faker ^1.9.1 -> satisfiable by fakerphp/faker[v1.9.1, ..., v1.13.0].                                                                                                                                                               - fzaninotto/faker 1.9.x-dev conflicts with fakerphp/faker v1.13.0.                                                                                                                                                                                                             - fzaninotto/faker 1.9.x-dev conflicts with fakerphp/faker v1.12.1.                                                                                                                                                                                                             - fzaninotto/faker 1.9.x-dev conflicts with fakerphp/faker v1.12.0.                                                                                                                                                                                                             - fzaninotto/faker 1.9.x-dev conflicts with fakerphp/faker v1.11.0.                                                                                                                                                                                                             - fzaninotto/faker 1.9.x-dev conflicts with fakerphp/faker v1.10.1.                                                                                                                                                                                                             - fzaninotto/faker 1.9.x-dev conflicts with fakerphp/faker v1.10.0.                                                                                                                                                                                                             - fzaninotto/faker 1.9.x-dev conflicts with fakerphp/faker 1.12.x-dev.                                                                                                                                                                                                          - Root composer.json requires fzaninotto/faker ^1.9.1 -> satisfiable by fzaninotto/faker[v1.9.1, v1.9.2, v1.9.2.x-dev, 1.9.x-dev (alias of dev-master)], fakerphp/faker[v1.9.1, v1.9.2, 1.9.x-dev].
--

**Comment by shalvah** [comment]
There's a problem with _your_ dependencies.

Look at this: https://travis-ci.com/github/knuckleswtf/scribe/jobs/461150341

The build passed on PHP 8. Faker 1.12 was installed. There's something in your deps locking you to 1.9.

**Comment by dacopavlov** [comment]
@shalvah, thank you, you are right. In the composer,json I found that "fakerphp/faker": "^1.9.1" was set like required. I removed the faker from composer.json, and set "knuckleswtf/scribe": "^2.5"
Now all looks OK!

**Pull request merged**
