### PR TITLE
feat: Add Laravel 11 Support

### PR DESCRIPTION
**Pull request by gabrielrbarbosa**
allow composer packages to versions ^11.0

### CODE REVIEW

**Comment by gabrielrbarbosa** [comment]
@shalvah

**Comment by codespearhead** [comment]
A stable version of Laravel 11 hasn't been released, has it?

If that's so, I don't think trying to support non-LTS versions of the framework is a good idea.

Also, when the time comes, the [tests](https://github.com/knuckleswtf/scribe/blob/master/.github/workflows/run-tests.yml) should be updated in this PR.

**Comment by shalvah** [comment]
I'll merge this PR, but it doesn't guarantee the package will correctly work (or even be installable) on Laravel 11.

**Comment by gabrielrbarbosa** [comment]
@shalvah Thanks! Just one conflict still remains:
 - shalvah/clara 3.1.0 requires symfony/console ^4.0|^5.0|^6.0
 and Laravel 11 requires ^7.0, should we update that repository or maybe remove it from composer.json since I didn't find any usage here in code searching for "clara".

**Comment by gabrielrbarbosa** [comment]
https://github.com/shalvah/clara/pull/4

**Comment by markwalet** [comment]
I see that this feature was merged to master a few weeks ago. I'm temporarily using `dev-master` to test my Laravel upgrade and everything looks okay. When can we (roughly) expect a stable release?

**Comment by shalvah** [comment]
I've tagged 4.34.0 now (although it's still not tested on L11)

**Comment by markwalet** [comment]
Thanks! From my tests the last few days, dev-master worked great on L11 :+1:

**Comment by shalvah** [comment]
Nice!

**Comment by cAstraea** [comment]
Sorry do you know how to make it pick up routes that now reside in the bootstrap/app.php ?  I had to get rid of the routes/api.php file because I wanted my routes prefixed like user/api and not api/user

**Comment by markwalet** [comment]
@cAstraea That does not look a Laravel 11 support issue to me. I think it is best to create a new ticket for that.

But AFAIK, Scribe should just pick up any registered routes.

**Pull request merged**
