### PR TITLE
Adding Support for UUID Type

### PR DESCRIPTION
**Pull request by Jiraiya43**
This pull request introduces support for UUID (Universally Unique Identifier) types within your application.

### CODE REVIEW

**Comment by shalvah** [comment]
I'm not sold on this. We try to restrict ourselves to the most common primitive data types, not subtypes. If we add a `uuid` type, what's stopping us from adding an `ip` type, or an `email` type?

**Comment by Jiraiya43** [comment]
In fact, when I submitted the PR, I had the same thought. However, I thought that rather than restrict the options, we could use Faker as a generator and stick to the types it offers. What particularly frustrated me was that when I renamed the field to "uuid", it generated an example UUID, but when I set the type to "uuid", an example"string" type was provided instead.

**Comment by shalvah** [comment]
That's an interesting proposal. Will need to consider it some more.

**Review by medeirosinacio — APPROVED** [review]

**Comment by shalvah** [comment]
> In fact, when I submitted the PR, I had the same thought. However, I thought that rather than restrict the options, we could use Faker as a generator and stick to the types it offers. What particularly frustrated me was that when I renamed the field to "uuid", it generated an example UUID, but when I set the type to "uuid", an example"string" type was provided instead.

I know it's been a while, but this is a good idea, and I could get behind it if you want to implement it. Esssentially:
- you can use any type provided by Faker
- Scribe will use that as a hint to generate the correct example

Closing this PR and making an issue from that.

**Pull request closed without merging**
