### PR TITLE
Fix sorting of multiple responses by status code

### PR DESCRIPTION
**Pull request by bram-pkg**
The `sortBy` function from Laravel does not modify the collection's sort order. It returns a new sorted collection.

### CODE REVIEW

**Comment by shalvah** [comment]
Thanks! Could you add a test for this?

**Comment by bram-pkg** [comment]
Yep, sure thing!

**Comment by bram-pkg** [comment]
@shalvah I've added some unit tests!

**Review by shalvah — APPROVED** [review]

**Comment by bram-pkg** [comment]
I've fixed the PHPStan error, my bad. It should be fine now.

**Pull request merged**
